### ISSUE TITLE
Multiple Stylesheets...

### ISSUE THREAD

**Issue by ghost** [FHSCodeClub/Old-Website#18]
Why do we have multiple stylesheets when we are tyring to make a uniform webpage?

**Comment by icyhydro** [comment]
I'd agree. We should have one stylesheet and if a page needs something unique, make a class or an ID.

**Comment by gallopinggoose6** [comment]
ok

**Comment by gallopinggoose6** [comment]
If the Stylesheet gets too messy, we can split it up again
Also, close this issue
