### ISSUE TITLE
Bugs with recent commits

### ISSUE THREAD

**Issue by gallopinggoose6** [FHSCodeClub/Old-Website#24]
Hi all, I see that there is a spacing bug in the brand new footer, that causes the text to be either really large, or really tiny, and it sometimes clips the girls who code photo. Depending on the width of your monitor.
I already have a fix almost complete, and that the problem will be resolved soon.

**Comment by icyhydro** [comment]
Fixed by #25 & #26.

**Comment by gallopinggoose6** [comment]
uh
for some reason, css is not working with the latest pull request...
the code works fine on all different screens, I tested it, but for some reason, on the github.io site, things aren't working...

**Comment by gallopinggoose6** [comment]
I see the problem now
