### ISSUE TITLE
How to handle downloads?

### ISSUE THREAD

**Issue by gallopinggoose6** [FHSCodeClub/Old-Website#31]
I believe it would be beneficial for the club to be able to download projects to either help them learn, or if they made something cool, they can share it to the world, currently I'm using the <a> download tag, which I learned at W3 schools, but it isn't working, and W3 said it will not work on safari.
the <a> download tag needs to be replaced with something, but what?

**Comment by gallopinggoose6** [comment]
Well downloading now works :-)

**Comment by gallopinggoose6** [comment]
I wouldn't close this, since the <a> download tag still doesn't work on mac... or does it? can you test that Icy?

**Comment by icyhydro** [comment]
Works on my computer, but to be honest, storing the jar in our repo is probably not the best thing to do. You'd want to make it it's own repository, or at least put it somewhere else.
